project4/network/urls.py
from django.urls import path

from . import views

app_name = 'network'

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("like/<int:post_id>", views.post_like, name="like"),
    path("<int:user_id>", views.userpage, name="user_page"),
    path("follow/<int:user_id>", views.follow_user, name="follow"),
    path("edit/<int:post_id>", views.edit_post, name="edit_post"),
    path("following/", views.following_posts, name="following_posts"),

]

project4/project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls", namespace='network')),
]

project4/network/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE , related_name='posts')
    text = models.TextField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)
    edit = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.text}"

    def like_count(self):
        return self.likes.all().count()
    

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="userliked")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='likes')
    

class Follow(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='followings')
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name='followers')

    def __str__(self):
        return f'{self.follower} followed {self.following}'

project4/network/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text',)
        labels = {
            'text' : False
        }
        widgets = {
            'text' : forms.Textarea(attrs={'placeholder':"What's happening?", 'class': 'form-control', 'id': 'post-form', 'rows':2}) 
        }

project4/network/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .forms import PostForm
from .models import User, Post, Like, Follow 
from django.contrib import messages
from django.contrib.auth.decorators import login_required
import json
from django.core.paginator import Paginator



def index(request):
   
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            newpost = form.save(commit=False)
            newpost.author = request.user
            newpost.save()
            messages.success(request, "Your post submited successfully.", 'success')
            return redirect('network:index')
        messages.error(request, 'Somthing went wrong!', 'error')
        return redirect('network:index')
    
    if request.method == 'GET':
        form = PostForm()
        posts = Post.objects.all().order_by('-created')
        posts_list = []
        for post in posts:
            liked = False
            if request.user.is_authenticated:        
                try:
                    post.likes.get(user=request.user)
                    liked = True
                except Like.DoesNotExist:
                    liked = False
            posts_list.append((post, liked))
        p = Paginator(posts_list, 10)
        page_number = request.GET.get('page')
        page_obj = p.get_page(page_number)
    return render(request, "network/index.html", {'posts': page_obj, 'postform' : form, 'postcount' : p.count})


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("network:index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("network:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("network:index"))
    else:
        return render(request, "network/register.html")

@login_required
def post_like(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    like, created = Like.objects.get_or_create(user=request.user, post=post)
    if not created:
        like.delete()
        liked = False
    else:
        liked = True

    return JsonResponse({'liked': liked, 'like_count': post.likes.count()})

@login_required
def userpage(request, user_id):

    user = User.objects.get(pk=user_id)

    try:
        request.user.followings.get(following_id=user)
        followed = True
    except Follow.DoesNotExist:
        followed = False
    
    follower = user.followers.all()
    following = user.followings.all()
    user_posts_list = []
    user_posts = user.posts.all().order_by('-created')
    liked = False
    for post in user_posts:
        try:
            post.likes.get(user=request.user)
            liked = True
        except Like.DoesNotExist:
            liked = False
        user_posts_list.append((post, liked))
        p = Paginator(user_posts_list, 10)
        page_number = request.GET.get('page')
        page_obj = p.get_page(page_number)
    return render(request, 'network/user-page.html', {'follower':follower, 'following': following, 'user': user, 'user_posts': page_obj, 'followed' : followed, 'postcount': p.count})


def follow_user(request, user_id):
    user = User.objects.get(pk=user_id)
    
    following, created = request.user.followings.get_or_create(following_id=user.id)
    followed = False
    if not created:
        following.delete()
        followed = False
    else: 
        followed = True
    follower_count = user.followers.all().count()
    return JsonResponse({'followed' : followed, 'follower_count' : follower_count})


def edit_post(request, post_id):
    post = Post.objects.get(pk=post_id)
    if request.method == 'PUT':
        data = json.loads(request.body)
        if 'text' in data:
            post.text = data['text']
            post.save()
            return JsonResponse({'status': 'success', 'post': post_id, 'new_text': post.text})

def following_posts(request):
    following = request.user.followings.all().values('following')
    posts = Post.objects.filter(author__in=following).order_by('-created')
    posts_list = []
    for post in posts:
        liked = False
        if request.user.is_authenticated:        
            try:
                post.likes.get(user=request.user)
                liked = True
            except Like.DoesNotExist:
                liked = False
        posts_list.append((post, liked))
        p = Paginator(posts_list, 10)
        page_number = request.GET.get('page')
        page_obj = p.get_page(page_number)
    return render(request, 'network/following.html', {'posts':page_obj, 'postcount': p.count})

project4/network/templates/network/alerts.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

project4/network/templates/network/following.html
{% extends 'network/layout.html' %}

{% block body %}

<div class="row">
    <div class="col-md-10 mx-auto">
      <h2>Followings</h2>
      <ul class="list-group">
        {% for post, liked in posts %}
        <li class="list-group-item" id="list-group-item">
          <div class="post-header">
            <div>
              <a class="post-author" href="{% url 'network:user_page' post.author.id %}">{{ post.author|title }}</a>
              <small class="text-muted">{{ post.created }}</small>
            </div>
  
            {% if post.author == request.user %}
            <button class="edit-post" data-postId="{{ post.id }}">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                class="bi bi-pencil-square" viewBox="0 0 16 16">
                <path
                  d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                <path fill-rule="evenodd"
                  d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z" />
              </svg>
            </button>
            {% endif %}
          </div>
          <div class="edit-form" id="edit-form{{ post.id }}" style="display: none;">
            <textarea id="edit-content-{{ post.id }}"></textarea>
            <button id="save" data-postid="{{ post.id }}">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                class="bi bi-check-circle" viewBox="0 0 16 16">
                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16" />
                <path
                  d="m10.97 4.97-.02.022-3.473 4.425-2.093-2.094a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05" />
              </svg>
            </button>
            <button id="cancel" data-postid="{{ post.id }}">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle"
                viewBox="0 0 16 16">
                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16" />
                <path
                  d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708" />
              </svg>
            </button>
          </div>
  
          <p id="post-text-{{ post.id }}">{{ post.text }}</p>
          <div class="post-footer">
            <button type="button" class="post-btn like-btn" data-postId="{{ post.id }}" id="like-btn">
              {% if not liked %}
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart"
                viewBox="0 0 16 16">
                <path
                  d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15" />
              </svg>
  
              {% else %}
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill"
                viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314" />
              </svg>
  
              {% endif %}
            </button>
            <span class="like-counter" id="like-count-{{ post.id }}">{{ post.like_count }}</span>
          </div>
        </li>
        {% empty %}
        <p>No follower!</p>
        {% endfor %}
      </ul>
    </div>
  </div>
  {% if postcount > 10 %}
  <nav aria-label="Page navigation example ">
    <ul class="pagination justify-content-center">
      {% if posts.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ posts.previous_page_number }}">Previous</a></li>
      {% else %}
      <li class="page-item disabled"><a class="page-link">Previous</a></li>
      {% endif %}
      {% if posts.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ posts.next_page_number }}">Next</a></li>
      {% else %}
      <li class="page-item disabled"><a class="page-link">Next</a></li>
      {% endif %}
    </ul>
  </nav>
  {% endif %}

{% endblock %}

project4/network/templates/network/index.html
{% extends "network/layout.html" %}

{% block body %}

<!-- Post Form -->
<form class="form-horizontal m-3" role="form" method="post" novalidate>
  {% csrf_token %}
  <div class="form-group">
    <div class="form-group">
      <label for="content" class="col-sm-2 control-label">
        <h4>{{ request.user }}:</h4>
      </label>
      <div class="col-sm-12">
        {{ postform }}
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary mt-1" id="post-submit-btn">Post</button>
      </div>
    </div>
</form>

<!-- Display Posts -->
<div class="row">
  <div class="col-md-10 mx-auto">
    <h2>Posts</h2>
    <ul class="list-group">
      {% for post, liked in posts %}
      <li class="list-group-item" id="list-group-item">
        <div class="post-header">
          <div>
            <a class="post-author" href="{% url 'network:user_page' post.author.id %}">{{ post.author|title }}</a>
            <small class="text-muted">{{ post.created }}</small>
          </div>

          {% if post.author == request.user %}
          <button class="edit-post" data-postId="{{ post.id }}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
              class="bi bi-pencil-square" viewBox="0 0 16 16">
              <path
                d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
              <path fill-rule="evenodd"
                d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z" />
            </svg>
          </button>
          {% endif %}
        </div>
        <div class="edit-form" id="edit-form{{ post.id }}" style="display: none;">
          <textarea id="edit-content-{{ post.id }}"></textarea>
          <button id="save" data-postid="{{ post.id }}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
              class="bi bi-check-circle" viewBox="0 0 16 16">
              <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16" />
              <path
                d="m10.97 4.97-.02.022-3.473 4.425-2.093-2.094a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05" />
            </svg>
          </button>
          <button id="cancel" data-postid="{{ post.id }}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle"
              viewBox="0 0 16 16">
              <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16" />
              <path
                d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708" />
            </svg>
          </button>
        </div>

        <p id="post-text-{{ post.id }}">{{ post.text }}</p>
        <div class="post-footer">
          <button type="button" class="post-btn like-btn" data-postId="{{ post.id }}" id="like-btn">
            {% if not liked %}
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart"
              viewBox="0 0 16 16">
              <path
                d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15" />
            </svg>

            {% else %}
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill"
              viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314" />
            </svg>

            {% endif %}
          </button>
          <span class="like-counter" id="like-count-{{ post.id }}">{{ post.like_count }}</span>
        </div>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>
{% if postcount > 10 %}
<nav aria-label="Page navigation example ">
  <ul class="pagination justify-content-center">
    {% if posts.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{ posts.previous_page_number }}">Previous</a></li>
    {% else %}
    <li class="page-item disabled"><a class="page-link">Previous</a></li>
    {% endif %}
    {% if posts.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ posts.next_page_number }}">Next</a></li>
    {% else %}
    <li class="page-item disabled"><a class="page-link">Next</a></li>
    {% endif %}
  </ul>
</nav>
{% endif %}
{% endblock %}

project4/network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <meta name="csrf-token" content="{{ csrf_token }}">

    <head>
        <title>{% block title %}Social Network{% endblock %}</title>
        
        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link href="{% static 'network/css/styles.css' %}" rel="stylesheet">
        
    </head>
    <body>
        {% include 'network/alerts.html' %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark p-4 py-2">
            <a class="navbar-brand" href="{% url 'network:index' %}">CS50W</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
          
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
              <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:user_page' request.user.id %}"><strong>{{ request.user.username }}</strong></a>
                    </li>
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'network:index' %}">All Posts</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:following_posts' %}">Following</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </nav>
        
        <div class="body">
            {% block body %}
            {% endblock %}
        </div>



        <!-- jQuery, Popper.js, and Bootstrap JS -->
    <script src="{% static 'network/js/index.js' %}" ></script>
    <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
    </body>
</html>

project4/network/templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'network:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'network:register' %}">Register here.</a>

{% endblock %}

project4/network/templates/network/register.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'network:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'network:login' %}">Log In here.</a>

{% endblock %}