project1/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'encyclopedia'

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:article>", views.article, name="article"),
    path("search/", views.search, name="search"),
    path("create/", views.create, name="create"),
    path("edit/<str:article>", views.edit, name="edit"),
    path("random_article/", views.randompage, name="ranom_article"),

]

project1/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls", namespace='encyclopedia'))
]

project1/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

project1/wiki/encyclopedia/forms.py
from django import forms
from .util import get_entry
from django.core.exceptions import ValidationError

class CreateForm(forms.Form):
    title = forms.CharField(max_length=50,label='Title', widget=forms.TextInput(attrs={'placeholder': 'Enter your title here.', 'class':'form-control form-control-sm'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Enter your desctiption here.', 'class':'form-control'}))

    def clean_title(self):
        title = self.cleaned_data['title'] 
        is_exist = get_entry(title)
        if is_exist is not None:
            raise ValidationError('This title is exist! change that.')
        return title
    
class EditForm(forms.Form):
    title = forms.CharField(max_length=50,label='Title', widget=forms.TextInput(attrs={'placeholder': 'Enter your title here.', 'class':'form-control form-control-sm'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Enter your desctiption here.', 'class':'form-control'}))

project1/wiki/encyclopedia/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.files.storage import default_storage
from . import util
from .forms import CreateForm, EditForm
from markdown2 import Markdown
import random


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def article(request, article):
    content = util.get_entry(article)
    title = 'Not found!'
    if content is not None:
        title = article
        markdowner = Markdown()
        content = markdowner.convert(content)

    return render(request, "encyclopedia/article.html", {'content' : content, 'title' : title})

def search(request):
    if request.method == 'GET':
        query = request.GET['q']
        content = util.get_entry(query)
        articles = util.list_entries()
        matched_list = []
        if content is not None:
            markdoner = Markdown()
            content = markdoner.convert(content)
            title = query
        else:
            for article in articles:
                article_lower = article.lower()
                if query in article_lower:
                    matched_list.append(article)
            title = 'Not found!'
               
    return render(request, "encyclopedia/article.html", {'content' : content,'title': title, 'matched_list':matched_list})

def create(request):
    form = CreateForm()
    if request.method == 'POST':
        form = CreateForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            title = cd['title']
            description = cd['description']
            util.save_entry(title=title, content=description)
            messages.success(request, f'Article "{title}" was successfully created!', 'success')
            return redirect('encyclopedia:article', article=title)

    return render(request, "encyclopedia/create.html", {'form': form})
        

def edit(request, article):
    content = util.get_entry(article)
    initial_data = {
        'title' : article,
        'description' : content
    }
    form = EditForm(initial=initial_data)
    if request.method == 'POST':
        form = EditForm(request.POST, initial=initial_data)
        if form.is_valid():
            cd = form.cleaned_data
            title = cd['title']
            description = cd['description']
            util.save_entry(title=title ,content=description)
            messages.success(request, f'Article "{title}" was successfully updated!')
            return redirect('encyclopedia:article', article=title)
    return render(request, 'encyclopedia/edit.html', {'form':form})

def randompage(request):
    article_counter = len(util.list_entries())
    random_int = random.randint(0, article_counter-1)
    rand_article = util.list_entries()[random_int]
    return redirect('encyclopedia:article', article=rand_article)

project1/wiki/encyclopedia/templates/encyclopedia/alerts.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

project1/wiki/encyclopedia/templates/encyclopedia/article.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    {% if content is None %}
        <h3>The requested page was not found!</h3>
        {% for article in matched_list %}
        <ul>
            <li><a href="{% url 'encyclopedia:article' article %}">{{ article }}</a></li>
        </ul>
        {% endfor %}
    {% else %}
        {{ content|safe }}
        <a href="{% url 'encyclopedia:edit' title %}" class="btn btn-secondary">Edit</a>
    {% endif %}


{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create
{% endblock %}

{% block body %}
    <form action="{% url 'encyclopedia:create' %}" method="post" class="form-group">
        {% csrf_token %}
        <br>
        {{ form.as_p }}
        <br>
        <input type="submit" value="Create" class="btn btn-success">
    </form>    

{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create
{% endblock %}

{% block body %}
    <form action="" method="post" class="form-group">
        {% csrf_token %}
        <br>
        {{ form.as_p }}
        <br>
        <input type="submit" value="Update" class="btn btn-warning">
    </form>    

{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:article' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        {% include 'encyclopedia/alerts.html' %}
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:ranom_article' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>