project5/finance_traker/finance_traker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('userprofile.urls', namespace='userprofile')),
]

project5/finance_traker/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.control_authentication, name='home'),
]

project5/finance_traker/userprofile/urls.py
from django.urls import path
from django.shortcuts import redirect
from . import views

app_name = 'userprofile'

urlpatterns= [
    # path('', views.userbase_view, name='user_profile'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('transaction/', views.transaction, name='transaction'),
    path('delete_transaction/<int:id>', views.delete_transaction, name='delete_transaction'),
    path('update_transaction/<int:id>/', views.update_transaction, name='update_transaction'),
    path('category/', views.category, name='category')
]

project5/finance_traker/userprofile/models.py
from django.db import models
from accounts.models import User
from django.db.models import Sum



class Category(models.Model):
    name = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}'

class Budget(models.Model):
    amount = models.DecimalField(decimal_places=2, max_digits=13)
    current_amount = models.DecimalField(decimal_places=2, max_digits=13)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='budget')
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"{self.user.username} - {self.category.name} - {self.amount}"
    
    
class Transaction(models.Model):
    TRANSACTION_TYPE = [
        ('income', 'Income'),
        ('expense', 'Expense'),
    ]
    name = models.CharField(max_length=225, blank=True, null=True)
    amount = models.DecimalField(decimal_places=2, max_digits=13)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    transaction_type = models.CharField(choices=TRANSACTION_TYPE, max_length=7)
    date = models.DateTimeField(auto_now_add=True)
    description = models.TextField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username} - {self.amount} - {self.transaction_type}"
    
    @classmethod
    def total_income(cls):
        result = cls.objects.filter(transaction_type='income').aggregate(total=Sum('amount'))
        return result['total'] or 0
    
    
    @classmethod
    def total_expense(cls):
        result = cls.objects.filter(transaction_type='expense').aggregate(total=Sum('amount'))
        return result['total'] or 0

project5/finance_traker/userprofile/forms.py
from django import forms
from .models import Budget, Category, Transaction
from django.core.exceptions import ValidationError

class CreateBudgetForm(forms.Form):
    amount = forms.DecimalField(decimal_places=2, max_digits=13, widget=forms.NumberInput(attrs={'placeholder' : 'Amount'}))
    category = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'placeholder' : 'Category'}))
    start_date = forms.DateField(widget=forms.DateInput(attrs={'type':'date'}))
    end_date = forms.DateField(required=False, widget=forms.DateInput(attrs={'type':'date'}))

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(CreateBudgetForm, self).__init__(*args, **kwargs)

    def clean_category(self):
        category_name = self.cleaned_data['category']
        try:
            category = Category.objects.get(name=category_name, user=self.request.user)
            raise ValidationError('This category already has a budget!')
        except Category.DoesNotExist:
            return category_name


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = '__all__'
        exclude = ('date','user')

        widgets = {
         'name' : forms.TextInput(attrs={'placeholder' : 'Name'}),
         'amount' : forms.NumberInput(attrs={'placeholder' : 'Amount'}),
         'description' : forms.TextInput(attrs={'placeholder' : 'Description'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].empty_label = 'Category'
        self.fields['transaction_type'].choices = [('', 'Type')] + list(self.fields['transaction_type'].choices)[1:]

project5/finance_traker/userprofile/views.py
from django.shortcuts import render
from django import views
from .forms import CreateBudgetForm, TransactionForm
from .models import Budget, Category, Transaction
from django.contrib import messages
from django.http import JsonResponse
from django.db.models import Sum
from django.contrib.auth.decorators import login_required
import json

@login_required
def userprofile_view(request):
    return render(request, 'base-user.html')
    

def dashboard(request):
    if request.method == 'POST':
        form = CreateBudgetForm(request.POST, request=request)
        if form.is_valid():
            cd = form.cleaned_data
            category = Category.objects.create(name=cd['category'], user=request.user)
            budget = Budget(
                user=request.user,
                amount=cd['amount'],
                current_amount=cd['amount'],
                category=category ,
                start_date=cd['start_date'],
                end_date=cd['end_date']
                )
            budget.save()
            new_balance = Budget.objects.aggregate(total=Sum('current_amount'))['total'] or 0
            return JsonResponse({'status': 'success', 'new_balance': new_balance, 'amount': cd['amount'], 'category' : cd['category']})
        else:
            return JsonResponse({'status': 'error', 'errors': form.errors})
    elif request.method == 'GET':
        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            balance = Budget.objects.aggregate(total=Sum('amount'))['total'] or 0
            transaction_expense = Transaction.objects.filter(transaction_type='expense').aggregate(total=Sum('amount'))['total'] or 0
            balance = balance - transaction_expense
            transaction_income = Transaction.objects.filter(transaction_type='income').aggregate(total=Sum('amount'))['total'] or 0
            balance = balance + transaction_income
            categories = Category.objects.all()
            total_income = Transaction.total_income()
            total_expense = Transaction.total_expense()
            budget_names = Budget.objects.all().values_list('category__name', flat=True)
            budget_amounts = Budget.objects.all().values_list('amount', flat=True)
            budget_amounts = [int(amount) for amount in budget_amounts]
            data = {
                'balance': balance,
                'categories': list(categories.values('id', 'name')),
                'total_income': total_income,
                'total_expense': total_expense,
                'labels': list(budget_names),
                'datasets': [{
                    'label': '# of Votes',
                    'data': list(budget_amounts),
                    'borderWidth': 1
                }]
            }
            return JsonResponse(data)
        else:
            return render(request, 'userprofile/dashboard.html')
    return JsonResponse({'status': 'error', 'message': 'Invalid request'})


def transaction(request):
    if request.method == 'POST':
        form = TransactionForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            try:
                category_budget = Budget.objects.get(user=request.user, category=cd['category'])
                if cd['transaction_type'] == 'income':
                    category_budget.current_amount += cd['amount']
                else:
                    category_budget.current_amount -= cd['amount']
                category_budget.save()
                new_transaction = form.save(commit=False)
                new_transaction.user = request.user
                new_transaction.save()
                return JsonResponse({
                    'status': 'success',
                    'message': 'Transaction saved!',
                    'transaction': {
                        'id' : new_transaction.id,
                        'name' : cd['name'],
                        'amount': cd['amount'],
                        'category': cd['category'].name,
                        'transaction_type': cd['transaction_type'],
                        'date' : new_transaction.date
                    },
                    
                })
            except Budget.DoesNotExist:
                return JsonResponse({'status': 'error', 'message': 'Category budget does not exist.'})
        return JsonResponse({'status': 'error', 'errors': form.errors})
    elif request.method == 'GET':
        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            categories = Category.objects.all().values('pk', 'name')
            transactions = Transaction.objects.filter(user=request.user).order_by('-date')
            transactions_data = list(transactions.values('id','name', 'category__name', 'amount', 'transaction_type', 'date'))
            return JsonResponse({'transactions': transactions_data,
                                 'categories' : list(categories)
                                 })
        else:
            return render(request, 'userprofile/transaction.html')
    return JsonResponse({'status' : 'error', 'message' : 'Invadid'})

def delete_transaction(request, id):
    print('this function')
    if request.method == 'DELETE':
        try:
            print('try block ')
            transaction = Transaction.objects.get(pk=id)
            print(f'I find transaciton{transaction}')
            budget = Budget.objects.get(category=transaction.category, user=request.user)
            print(f'I find {budget}')
            if transaction.transaction_type == 'expense':
                print('this is if block')
                print(transaction.transaction_type)
                budget.current_amount += transaction.amount
            else:
                print('this is else block')
                print(transaction.transaction_type)
                budget.current_amount -= transaction.amount
            print('save that current amount!')
            budget.save()
            transaction.delete()
            return JsonResponse({
                'success' : True,
                'transaction_id' : id 
                                 })
        except Transaction.DoesNotExist:
            return JsonResponse({'error' : 'Transaction not found!'}, status=404)
        except Budget.DoesNotExist:
            return JsonResponse({'error': 'Budget not found for this transaction!'}, status=404)
    return JsonResponse({'error': 'Method not allowed!'}, status=405)


def update_transaction(request, id):
    transaction = Transaction.objects.get(pk=id)
    transaction_type = transaction.transaction_type
    transaction_category = transaction.category
    if request.method == 'GET':
        return JsonResponse({
            'transaction' : {
                'id' : transaction.id,
                'name' : transaction.name,
                'amount' : transaction.amount,
                'transaction_type' : transaction.transaction_type,
                'category' : {
                    'id' : transaction.category.id,
                    'name' : transaction.category.name
                }
            }
        })
    elif request.method == 'PUT':
        data = json.loads(request.body)
        form = TransactionForm(data, instance=transaction)
        if form.is_valid():
            update_transaction = form.save(commit=False)
            budget = Budget.objects.get(user=request.user ,category=transaction_category)
            if update_transaction.transaction_type != transaction_type:
                if update_transaction.transaction_type == 'expense':
                    transactions = Transaction.objects.filter(user=request.user, category=transaction_category, transaction_type='expense')
                    amount_expense = transactions.aggregate(total=Sum('amount'))['total'] or 0
                    double = transaction.amount * 2
                    budget.current_amount -= double
                    print(f'all amount of expence is {amount_expense}\n and my transaction is {transaction.amount}\n so we double it:{transaction.amount * 2} and - form the budget current {budget.current_amount} and my budget current will be {budget.current_amount - (transaction.amount * 2)}')

                else:
                    transactions = Transaction.objects.filter(user=request.user, category=transaction_category, transaction_type='income')
                    amount_income = transactions.aggregate(total=Sum('amount'))['total'] or 0
                    double = transaction.amount * 2
                    budget.current_amount += double
                    print(f'befor is {transaction_type}, after {update_transaction.transaction_type}')
                    print(f'All incomes are:{amount_income}\nThis transaction amount is: {transaction.amount}\n double it: {transaction.amount * 2}\n all transactions amount income + this transaction amount {amount_income + transaction.amount} the budget current should be: {budget.current_amount - (amount_income + transaction.amount)}')

            budget.save()
            update_transaction.user = request.user
            update_transaction.save()
            return JsonResponse({
                'status' : 'success',
                'message' : 'Transition updated successfully!',
                'transaction' : {
                    'id' : update_transaction.id,
                    'name' : update_transaction.name,
                    'amount' : update_transaction.amount,
                    'transaction_type' : update_transaction.transaction_type,
                    'date' : update_transaction.date,
                    'category' : {
                        'id' : update_transaction.category.id,
                        'name' : update_transaction.category.name
                    }
                }
            })
        else:
            return JsonResponse({'errors': form.errors}, status=400)


def category(request):
    budgets = Budget.objects.all()
    budgets_list = []
    for budget in budgets:

project5/finance_traker/userprofile/templates/userprofile/category.html
<section class="categories">

    {% for budget, budget_percent in budgets %}
    <div class="category">
        <h2>{{ budget.category }}</h2>
        <p>{{ budget.current_amount|floatformat:0 }}$/{{ budget.amount|floatformat:0 }}$</p>
        <div class="line-bar">
            {% if budget_percent > 100%}
            <div class='status-bar' style="width: 100%;"></div>
            {% else %}
            <div class='status-bar' style="width: {{ budget_percent }}%;"></div>
            {% endif %}
        </div>
        <div class="percent">
            <small>{{ budget_percent }}%</small>
        </div>
    </div>
    {% endfor %}
    
</section>

project5/finance_traker/userprofile/templates/userprofile/dashboard.html
{% load humanize %}
<section class="dashboard-sec">

    <button id="createbg-btn" type="button" data-toggle="modal" data-target="#exampleModalCenter"> <label
            for="createbg-btn"">
        <svg xmlns=" http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-plus"
            viewBox="0 0 16 16">
            <path
                d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4" />
            </svg>
        </label class='budget-btn'>
        <p>Create Budget</p>
    </button>

    <section class="account-summery">
        <div class="balance">
            <h6>Total balance</h6>
            <h4></h4>
        </div>
        <div class="income">
            <h6>Income</h6>
            <h4></h4>
        </div>
        <div class="expense">
            <h6>Expense</h6>
            <h4></h4>
        </div>
    </section>

    <section class="category-chart">
        <div class="col-xs-12 text-center">
        </div>
        <div class="dounut-chart">
            <p id="nochart-alert" class="hidden">"No data available. Create a budget to view the chart."</p>
            <canvas id="myChart"></canvas>
        </div>

    </section>
    <div class="createbg-form-container hidden">
        <div id="response-message"></div>
        <div class="createbg-form">
            <button type="button" class="btn-close" aria-label="Close"></button>
            <h3>Create Your Budget</h3>
            <p>Take control of your finances by setting up a personalized budget.</p>
            <form id="formbg" action="" method="post">
                {% csrf_token %}
                <input type="number" name="amount" placeholder="Amount" required="" id="id_amount">
                <input type="text" name="category" placeholder="Category" maxlength="200" required="" id="id_category">
                <div>
                    <label for="start_inp">Start at:</label>
                    <div id="start_inp">
                        <input type="date" name="start_date" required="" id="id_start_date">
                    </div>
                </div>

                <div>
                    <label for="end_inp">to:</label>
                    <div id="end_inp">
                        <input type="date" name="end_date" id="id_end_date">
                    </div>
                </div>
                <input class="submit-cb" type="submit" value="create">
            </form>
        </div>
    </div>
    
</section>

project5/finance_traker/userprofile/templates/userprofile/transaction.html
<div class="transaction-content">
<button id="createTr-btn" type="button" data-toggle="modal" data-target="#exampleModalCenter">
    <label for="createTr-btn"">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
        <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
    </svg>
    </label class='transaction-btn'><p>Add Transaction</p>
</button>

<div class="createTr-form-container hidden">
    <div id="response-message"></div>
    <div class="createTr-form">
        <button type="button" class="btn-close" aria-label="Close"></button>
        <h3>Create Your Budget</h3>
        <p>Take control of your finances by setting up a personalized budget.</p>
        <form id="formTr" action="" method="post">
            <div class="fields">
                {% csrf_token %}
                <input type="text" name="name" placeholder="Name" maxlength="225" id="id_name" data-ddg-inputtype="identities.fullName">
                <input type="number" name="amount" placeholder="Amount" step="0.01" required="" id="id_amount" data-ddg-inputtype="unknown">
                <select name="category" required="" id="id_category" data-ddg-inputtype="unknown">
                    <option value="" selected="">Category</option>
                  </select>
                  <select name="transaction_type" required="" id="id_transaction_type">
                    <option value="" selected="">Type</option>
                    <option value="income">Income</option>
                    <option value="expense">Expense</option>
                  </select>
            </div>
            <input type="text" name="description" placeholder="Description" id="id_description">
        <input class="submit-tr" type="submit" value="Add">
        </form>

    </div>
</div>
<br>
<section>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Category</th>
                <th scope="col">Date</th>
                <th scope="col">Amount</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody id="transactionTableBody">
        <tr>
        </tr>
        </tbody>
      </table>
</section>