project2/commerce/auctions/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'auctions'

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:listing_id>", views.listing_details, name="listing_details"),
    path("close/<int:listing_id>", views.listing_close, name="listing_close"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create", views.create, name="create"),
    path("watchlist", views.whatchlist, name="watchlist"),
    path("watchlist/<int:listing_id>", views.add_watchlist, name="add_watchlist"),
    path("category/", views.category, name="category"),
    path("category/<int:category_id>", views.category_details, name="category_details"),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project2/commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin", admin.site.urls),
    path("", include("auctions.urls", namespace='auctions'))
]

project2/commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

class Listing(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    bid = models.DecimalField(max_digits=6, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.URLField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    watchlist = models.ManyToManyField(User, blank=True, related_name='watchlists')
    
    def __str__(self):
        return f'{self.title} created by {self.author}'

class Bids(models.Model):
    amount = models.DecimalField(decimal_places=2, max_digits=6)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name='bids')
    created = models.DateTimeField(auto_now_add=True)


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)

project2/commerce/auctions/forms.py
from django import forms
from .models import Listing, Bids, Comment
from django.core.exceptions import ValidationError

class CreateListinForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            if not isinstance(field, forms.ImageField):
                field.widget.attrs['class'] = 'form-control'
    
    class Meta():
        model = Listing
        fields = '__all__'
        exclude = ['author', 'active']
        widgets = {
            'description' : forms.Textarea(attrs={'placeholder' : 'Enter your description here.'}),
            'title' : forms.TextInput(attrs={'placeholder' : 'Enter your title here.'}),
            'bid' : forms.NumberInput(attrs={'placeholder' : 'Bid start from...'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
        }

class BidForm(forms.ModelForm):

    class Meta:
        model = Bids
        fields = ['amount']
        labels = {
            'amount' : False
        }
        widgets = {
            'amount' : forms.NumberInput(attrs={'class' : 'form-control', 'placeholder' : 'Enter amount'})
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

        widgets = {
            'text' : forms.TextInput(attrs={'class' : 'form-control col-md-11', 'placeholder': 'Write the comment...'})
        }

project2/commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import CreateListinForm, BidForm, CommentForm
from .models import User, Listing, Bids, Comment, Category
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError


def index(request):
    listings = Listing.objects.filter(active=True)
    listing_list = []
    whatchlist_count = ''
    if request.user.is_authenticated:
        whatchlist_count = request.user.watchlists.all().count
    for listing in listings:
        is_watchlisted = False
        if request.user in listing.watchlist.all():
            is_watchlisted = True
        listing_list.append((listing, is_watchlisted))

    return render(request, "auctions/index.html", {'listsing_list' : listing_list, 'whatchlist_count': whatchlist_count})


def listing_details(request, listing_id):
    listing = Listing.objects.get(pk=listing_id)
    bid_form = BidForm()
    bids = listing.bids.all()
    winner_user = None
    if bids:
        winner_user = Bids.objects.filter(listing=listing_id).order_by('-amount').latest('created').user
    whatchlist_count = ''
    if request.user.is_authenticated:
        whatchlist_count = request.user.watchlists.all().count
    comment_form = CommentForm()
    comments = Comment.objects.filter(listing=listing).order_by('-created')

    if request.method == 'POST':
        if 'bid_submit' in request.POST:
            bid_form = BidForm(request.POST)
            if bid_form.is_valid():
                if listing.bid >= bid_form.cleaned_data['amount']:
                    messages.warning(request, 'Your bid must be grater than current bid!', 'warning')
                    return redirect('auctions:listing_details', listing_id=listing.id)
                new_bid = bid_form.save(commit=False)
                new_bid.user = request.user
                new_bid.listing = listing
                new_bid.save()
                listing.bid = new_bid.amount
                listing.save()
                messages.success(request, 'Your bid submited successfully.', 'success')
                return redirect('auctions:index')
        elif 'comment_submit' in request.POST:
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.author = request.user
                comment.listing = listing
                comment.save()
                messages.success(request, 'Your commetn submited successfully.')
            else:
                messages.warning(request, 'Somthing went wrong!.')
            return redirect('auctions:listing_details', listing.id)

                
    return render(request, 'auctions/listing-details.html', {
                                                            'listing':listing,
                                                            'bid_form' : bid_form,
                                                            'comment_form': comment_form,
                                                            'comments' : comments,
                                                            'winner_user':winner_user,
                                                            'comments' : comments,
                                                            'whatchlist_count' : whatchlist_count
                                                            })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")

@login_required
def create(request):
    form = CreateListinForm()
    whatchlist_count = ''
    if request.user.is_authenticated:
        whatchlist_count = request.user.watchlists.all().count
    if request.method == 'POST':
        form = CreateListinForm(request.POST, request.FILES)
        if form.is_valid():
            listing = form.save(commit=False)
            listing.author = request.user
            listing.save()
            # Category.objects.create(name=listing.category)
            messages.success(request, 'Your list created successfully!', 'success')
            return redirect('auctions:index')
        else:
            print(form.errors)
            messages.warning(request, 'Somthing wrong!', 'warning')
            return redirect('auctions:create')
            

    return render(request, 'auctions/create.html', {'form' : form, 'whatchlist_count' : whatchlist_count})

@login_required
def whatchlist(request):
    whatchlist_count = ''
    if request.user.is_authenticated:
        whatchlist_count = request.user.watchlists.all().count
    watchlists = request.user.watchlists.all
    return render(request, 'auctions/watchlist.html', {'watchlists' : watchlists, 'whatchlist_count':whatchlist_count})


@login_required
def add_watchlist(request, listing_id):
    listing = Listing.objects.get(id=listing_id)

    if request.user in listing.watchlist.all():
        listing.watchlist.remove(request.user)
        messages.success(request, f'{listing.title} removed from your watchlist!')
    else:
        listing.watchlist.add(request.user)
        messages.success(request, f'{listing.title} added to your watchlist.')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def listing_close(request, listing_id):
    listing = Listing.objects.get(pk=listing_id)
    if listing.author == request.user:
        listing.active = False
        listing.save()
        messages.success(request, 'Your acutions closed!', 'success')
        return redirect('auctions:watchlist')
    return render(request, 'auctions/listing-details.html')

def category(request):
    categorys =  Category.objects.all()
    whatchlist_count = ''
    if request.user.is_authenticated:
        whatchlist_count = request.user.watchlists.all().count
    return render(request, 'auctions/category.html', {'categorys' : categorys, 'whatchlist_count':whatchlist_count})

def category_details(request, category_id):
    whatchlist_count = ''
    if request.user.is_authenticated:
        whatchlist_count = request.user.watchlists.all().count
    category_lisings =  Listing.objects.filter(category=category_id)
    listing_list = []
    for listing in category_lisings:
        is_watchlisted = False
        if request.user in listing.watchlist.all():
            is_watchlisted = True
        listing_list.append((listing, is_watchlisted))
    print(listing_list)
    return render(request, 'auctions/category-details.html', {'listing_list' : listing_list, 'whatchlist_count':whatchlist_count})

project2/commerce/auctions/templates/auctions/alerts.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

project2/commerce/auctions/templates/auctions/category-details.html
{% extends "auctions/layout.html" %}

{% block body %}
<h2>Create Listings</h2>
<main>
  <article class="icontainer">
    {% for listing, is_watchlisted in listing_list %}
    <div class="card-item">
      <a class="add-wl-btn" href="{% url 'auctions:add_watchlist' listing.id %}">
        {% if not is_watchlisted %}
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" id="add-wl-icon"
          class="bi bi-plus-circle-fill" viewBox="0 0 16 16">
          <path
            d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3z" />
        </svg>
        {% else %}
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" id="add-wl-icon"
          class="bi bi-dash-circle-fill" viewBox="0 0 16 16">
          <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M4.5 7.5a.5.5 0 0 0 0 1h7a.5.5 0 0 0 0-1z" />
        </svg>
        {% endif %}
      </a>
      <a class="card-link" href="{% url 'auctions:listing_details' listing.id %}">
        <div class="image-container">
          <img src="{{ listing.image }}" alt="">
        </div>
        <div class="listing-content">
          <h1 class="listing-title">{{ listing.title|truncatechars:30 }}</h1>
          <p class="listing-txt">{{ listing.description|truncatechars:85 }}</p>
          <h5 class="listing-bid">{{ listing.bid }}$</h5>
          <p class="listing-author">Listed by: {{ listing.author }}</p>
        </div>
      </a>
    </div>
    {% endfor %}
  </article>
</main>
{% endblock %}

project2/commerce/auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Categorys</h2>
    <div class="container">
        <div class="row">
            {% for category in categorys %}
                <div class="col-md-3 mb-3">
                    <a class="btn btn-dark" href="{% url 'auctions:category_details' category.id %}" class="d-block p-3 border rounded">
                        {{ category.name }}
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

project2/commerce/auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Create Listings</h2>
    <form action="" method="post" class="form-group" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        {{ form.title.label_tag }}
        {{ form.title }}
        <br>
        {{ form.description.label_tag }}
        {{ form.description }}
        <br>
        <div class="form-row">
            <div class="col-md-2 mb-3">
                {{ form.bid.label_tag }}
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroupPrepend">$</span>
                    </div>
                    {{ form.bid }}
                </div>
            </div>
            <div class="col-md-2 mb-3">
                {{ form.category.label_tag }}
                {{ form.category }}
                
            </div>
            
        </div>
            
        {{ form.image.label_tag }}
        {{ form.image }}
        <br>
        <input type="submit" name="submit" id="" value="Create" class="btn btn-success">
    </form>
{% endblock %}

project2/commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
<h1>Active Listings</h1>
<main>
  <article class="icontainer">
    {% for listing, is_watchlisted in listsing_list %}
    <div class="card-item">
      <a class="add-wl-btn" href="{% url 'auctions:add_watchlist' listing.id %}">
        {% if not is_watchlisted %}
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" id="add-wl-icon"
          class="bi bi-plus-circle-fill" viewBox="0 0 16 16">
          <path
            d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3z" />
        </svg>
        {% else %}
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" id="add-wl-icon"
          class="bi bi-dash-circle-fill" viewBox="0 0 16 16">
          <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M4.5 7.5a.5.5 0 0 0 0 1h7a.5.5 0 0 0 0-1z" />
        </svg>
        {% endif %}
      </a>
      <a class="card-link" href="{% url 'auctions:listing_details' listing.id %}">
        <div class="image-container">
          <img src="{{ listing.image }}" alt="list-image">
        </div>
        <div class="listing-content">
          <h1 class="listing-title">{{ listing.title|truncatechars:30 }}</h1>
          <p class="listing-txt">{{ listing.description|truncatechars:85 }}</p>
          <h5 class="listing-bid">{{ listing.bid }}$</h5>
          <p class="listing-author">Listed by: {{ listing.author }}</p>
        </div>
      </a>
    </div>
    {% endfor %}
  </article>
</main>

{% endblock %}

project2/commerce/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
        <link href="{% static 'auctions/listing-detail.css' %}" rel="stylesheet">
        <style>
            #add-wl-icon {
            filter: drop-shadow(0px 3px 4px rgba(0, 0, 0, 0.5));
        }
        </style>
    </head>
    <body>
        <nav class="navbar navbar-dark bg-dark">
            <ul class="nav" style="color: white;">
                <a class="navbar-brand" href="#">CS50</a>
                <li class="nav-item">
                    <a class="nav-link btn btn-sm btn-outline-light mr-3" href="{% url 'auctions:index' %}">Active Listings</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn btn-sm btn-outline-light mr-3" href="{% url 'auctions:category' %}">Categorys</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link btn btn-sm btn-outline-light mr-3" href="{% url 'auctions:create' %}">Create Listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn btn-sm btn-outline-light mr-3" href="{% url 'auctions:watchlist' %}">Watchlist <span class="badge badge-light">{{whatchlist_count}}</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn btn-sm btn-outline-danger" href="{% url 'auctions:logout' %}">Log Out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link btn btn-sm btn-outline-light mr-3" href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn btn-sm btn-outline-light mr-3" href="{% url 'auctions:register' %}">Register</a>
                </li>
                {% endif %}
            </ul>
        </nav>
        <br>
        {% include 'auctions/alerts.html' %}
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

project2/commerce/auctions/templates/auctions/listing-details.html
{% extends "auctions/layout.html" %}

{% block body %}

    <main>
        <article class="listing-post">
            <img src="{{ listing.image }}" alt="Blog Thumbnail" class="listing-image">
            <div class="listing-content">
                <h1 class="listing-title">{{ listing.title }}</h1>
                <p class="listing-description">{{ listing.description }}</p>
                <p class="listing-bid">{{ listing.bid }}$</p>
                {% if listing.active %}
                {% if listing.author != request.user %}
                <form action="" method="post" class="form-row justify-content-center">
                    <div class="form-group mx-sm-3 mb-2">
                        {% csrf_token %}
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="inputGroupPrepend">$</span>
                            </div>
                            {{ bid_form.amount }}
                        </div>
                    </div>
                    <div class="form-group mx-sm-3 mb-2">
                        <input type="submit" name="bid_submit" value="Submit" class="btn btn-primary mb-2">
                    </div>
                </form>
                {% else %}
                <div class="form-row justify-content-center">
                    <a class="btn btn-danger" href="{% url 'auctions:listing_close' listing.id %}">Close Auction</a>
                </div>
                {% endif %}
                {% else %}
                {% if request.user == winner_user %}
                <p class="text-center alert alert-success font-weight-bold">Success! You have won the auction for the {{ listing.title }}!</p>
                {% else %}
                <p class="text-center alert alert-danger font-weight-bold">This auction is closed by author and "{{ winner_user|capfirst  }}" is the winner.</p>
                {% endif%}
                {% endif%}
                <p class="listing-author">Listed by: {{ listing.author }}</p>
            </div>
            <br>
            <h3>Leave a comment</h3>
            <form action="" method="post" class="form-inline">
                {% csrf_token %}
                {{ comment_form.text }}
                <input type="submit" value="send" name="comment_submit" class="btn btn-primary">
            </form>
            <br>
            {% for comment in comments %}
            <div class="card">
                <h5 class="card-header">{{ comment.author }}</h5>
                <div class="card-body">
                    <p class="card-text">{{ comment.text }}</p>
                </div>
            </div>
            <br>
            {% empty %}
            <p>No comments yet</p>
            {% endfor %}
           
        </article>
    </main>

    
{% endblock %}

project2/commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

project2/commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}

project2/commerce/auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Your Watchlist</h2>

    <main>
  <article class="icontainer">
      {% for watchlist in watchlists %}
      <div class="card-item">
        <a class="add-wl-btn" href="{% url 'auctions:add_watchlist' watchlist.id %}">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" id="add-wl-icon" class="bi bi-dash-circle-fill" viewBox="0 0 16 16">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M4.5 7.5a.5.5 0 0 0 0 1h7a.5.5 0 0 0 0-1z"/>
        </svg>
        </a>
        <a class="card-link" href="{% url 'auctions:listing_details' watchlist.id %}">
          <div class="image-container">
            <img src="{{ watchlist.image }}" alt="">
          </div>
          <div class="listing-content">
            <h1 class="listing-title">{{ watchlist.title|truncatechars:30 }}</h1>
            <p class="listing-txt">{{ watchlist.description|truncatechars:85 }}</p>
            <h5 class="listing-bid">{{ watchlist.bid }}$</h5>
            <p class="listing-author">Listed by: {{ watchlist.author }}</p>
          </div>
        </a>
      </div>
      {% endfor %}
      </article>
    </main>
{% endblock %}